---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - git
  - tree
  - httpie
  - curl
  - wget
  - kubectl
  - kubernetes-helm
  - zsh
  - go
  - hugo
  - vim
  - ag
  - dash
  - ctags

# homebrew cask applications
cask_applications:
  - iterm2
  - docker
  - vagrant
  - emacs
  - alfred
